// Generated by LiveScript 1.2.0
var browserify, gulp, gulpAutoprefixer, gulpStylus, gulpLivescript, vinylBuffer, vinylSourceStream;
browserify = require('browserify');
gulp = require('gulp');
gulpAutoprefixer = require('gulp-autoprefixer');
gulpStylus = require('gulp-stylus');
gulpLivescript = require('gulp-livescript');
vinylBuffer = require('vinyl-buffer');
vinylSourceStream = require('vinyl-source-stream');
gulp.task('stylus', function(){
  var distDest;
  distDest = './css';
  return gulp.src(['./src/stylus/main.styl', './src/stylus/app.styl']).pipe(gulpStylus({
    'include css': true
  })).pipe(gulp.dest(distDest));
});
gulp.task('js', function(){
  var distDest;
  distDest = './js';
  return browserify('./src/ls/app.js').bundle().pipe(vinylSourceStream('app.js')).pipe(gulp.dest(distDest));
});
gulp.task('watch', function(){
  gulp.watch(['./src/stylus/**/*.styl', './src/ls/**/*.ls'], ['stylus', 'js']);
});
gulp.task('default', ['stylus', 'js']);