// Generated by LiveScript 1.2.0
var m, r, Student, Controller;
m = require('mithril');
r = require('ramda');
Student = require('./../models/student');
Controller = (function(){
  Controller.displayName = 'Controller';
  var prototype = Controller.prototype, constructor = Controller;
  function Controller(){
    this.studentId = m.route.param('id');
    Student.store.cards = Student.cards(this.studentId);
  }
  prototype.onunload = function(e){
    return Student.sendStudentResults();
  };
  prototype.nextCard = function(){
    var ref$, cards, hints, studentName, card, hint, content;
    ref$ = Student.store.cards(), cards = ref$.cards, hints = ref$.hints, studentName = ref$.studentName;
    card = cards.shift();
    hint = r.find(r.propEq('deckId', card.deckId))(hints);
    return content = {
      title: studentName,
      hint: hint ? hint.hint : '',
      card: card.content
    };
  };
  return Controller;
}());
module.exports = Controller;