// Generated by LiveScript 1.2.0
var html5, setting, m, selectDeck, editDeck, newDeck, slice$ = [].slice;
html5 = require('./components/html5');
setting = require('./components/setting');
m = require('mithril');
selectDeck = function(it){
  return m('div', [
    m('a', {
      config: m.route,
      href: "/app/decks/" + it.deckId
    }, [m('button', it.deckName)]), m('button', {
      onclick: this.editName.bind(this, it.deckId)
    }, 'Edit')
  ]);
};
editDeck = function(deck){
  var cb, cb_, ref$;
  cb = slice$.call(arguments, 1);
  cb_ = (ref$ = cb[0]) != null
    ? ref$
    : this.newName.bind(this, deck.deckId);
  return m('div', [
    m('input#edit[type="text"]', {
      value: deck.deckName,
      config: function(e){
        e.onkeypress = function(){
          switch (false) {
          case e.keyCode !== 13:
            return cb_;
          }
        };
        e.focus();
      }
    }), m('button', {
      onclick: cb_
    }, 'Submit')
  ]);
};
newDeck = function(){
  var newDeck;
  switch (false) {
  case !this.newDeck:
    newDeck = {};
    newDeck.deckId = -1;
    newDeck.deckName = 'Deck Name';
    return editDeck.call(this, newDeck, this.createDeck.bind(this));
  default:
    return m('div.new-deck', [m('a', {
      onclick: this.editNewDeck.bind(this)
    }, [m('button', 'New Deck Name')])]);
  }
};
module.exports = function(ctrl){
  var decks, result;
  decks = ctrl.decks || [];
  return result = html5(['/css/app.css'], setting('Decks', decks.map(function(it){
    switch (false) {
    case !it.edit:
      return editDeck.call(ctrl, it);
    default:
      return selectDeck.call(ctrl, it);
    }
  }).concat(newDeck.call(ctrl))));
};