// Generated by LiveScript 1.2.0
var html5, header, setting, m;
html5 = require('./components/html5');
header = require('./components/header');
setting = require('./components/setting');
m = require('mithril');
module.exports = function(ctrl){
  var students, result;
  students = ctrl.students;
  return result = html5(['/css/app.css'], setting('Students', students().map(function(it){
    return m("a", {
      config: m.route,
      href: "/students/" + it.student_id
    }, [m('button', it.student_name)]);
  })));
};