// Generated by LiveScript 1.2.0
var student, students, studentList, studentView, m, app;
student = require('./controllers/student');
students = require('./controllers/students');
studentList = require('./views/student-list');
studentView = require('./views/student-view');
m = require('mithril');
app = function(view, controller){
  return {
    view: view,
    controller: controller
  };
};
m.route.mode = 'pathname';
m.route(document, '/app/students', {
  '/app/students': app(studentList, students),
  '/app/students/:id': app(studentView, student)
});