// Generated by LiveScript 1.2.0
var studentDeck, studentQuiz, students, studentDeckView, studentList, studentQuizView, m, app;
studentDeck = require('./controllers/student-deck');
studentQuiz = require('./controllers/student-quiz');
students = require('./controllers/students');
studentDeckView = require('./views/student-deck-view');
studentList = require('./views/student-list');
studentQuizView = require('./views/student-quiz-view');
m = require('mithril');
app = function(view, controller){
  return {
    view: view,
    controller: controller
  };
};
m.route.mode = 'pathname';
m.route(document, '/', {
  '/app/students': app(studentList, students),
  '/app/students/:id/quiz': app(studentQuizView, studentQuiz),
  '/app/students/:id/decks': app(studentDeckView, studentDeck)
});