// Generated by LiveScript 1.2.0
var m, titleCase, link;
m = require('mithril');
titleCase = function(s){
  return s.replace(/\w\S*/g, function(txt){
    return txt.charAt(0).toUpperCase() + txt.substr(1).toLowerCase();
  });
};
link = function(condition, route){
  switch (false) {
  case !(condition && route):
    return m("a[href='" + route + "']", {
      config: m.route
    }, titleCase(route.slice(route.lastIndexOf('/') + 1)));
  default:
    return '';
  }
};
module.exports = function(){
  var student, quizLink, studentDecks, decksLink, ifNotSelf, result;
  student = m.route.param('id');
  quizLink = "/app/students/" + student + "/quiz";
  studentDecks = "/app/students/" + student + "/decks";
  decksLink = '/app/decks';
  ifNotSelf = function(link){
    return m.route() !== link;
  };
  return result = m('header', [m('a[href="/"]', [m('h1', m.trust('L&aelig;re'))]), m('nav', [link(ifNotSelf('/app/students'), '/app/students'), link(student && ifNotSelf(quizLink), quizLink), link(student && ifNotSelf(studentDecks), studentDecks), link(!student && ifNotSelf(decksLink), decksLink), m('a[href="/api/logout"]', 'Log Out')])]);
};