// Generated by LiveScript 1.2.0
var m;
m = require('mithril');
module.exports = function(styles, content){
  var result;
  return result = [
    m('head', [
      m('meta', {
        charset: 'UTF-8'
      }), m('title', m.trust('L&aelig;re | Spaced Repetition for Kids!')), styles.map(function(it){
        return m('link', {
          rel: 'stylesheet',
          href: it
        });
      })
    ]), m('body', content)
  ];
};