// Generated by LiveScript 1.2.0
var m;
m = require('mithril');
module.exports = function(content){
  var result;
  return result = [m('.cards', [m('header', m('h1', content.title)), m('.hint', content.hint), m('.card', content.card), m('a.next.fa.fa-arrow-circle-o-right')])];
};