// Generated by LiveScript 1.2.0
var m;
m = require('mithril');
module.exports = function(title, content){
  var result;
  return result = [m('.settings', [m('header', m('h1', title)), m('.content', content)])];
};