// Generated by LiveScript 1.2.0
var m, Deck;
m = require('mithril');
Deck = {
  cards: function(deckId){
    return m.request({
      method: 'GET',
      url: "/api/decks/" + deckId + "/cards"
    });
  },
  changeCardName: function(deckId, cardId, newName){
    return m.request({
      method: 'PUT',
      url: "/api/decks/" + deckId + "/cards",
      data: {
        content: newName,
        cardId: cardId
      }
    });
  },
  deleteCard: function(deckId, cardId){
    return m.request({
      method: 'DELETE',
      url: "/api/decks/" + deckId + "/cards",
      data: {
        cardId: cardId
      }
    });
  },
  createCard: function(deckId, content){
    return m.request({
      method: 'POST',
      url: "/api/decks/" + deckId + "/cards",
      data: {
        content: content
      }
    });
  }
};
module.exports = Deck;