// Generated by LiveScript 1.2.0
var m, Student;
m = require('mithril');
Student = {};
Student.cards = function(studentId){
  return m.request({
    method: 'GET',
    url: "/api/students/" + studentId + "/cards"
  });
};
Student.sendStudentResult = function(studentId, performance){
  return m.request({
    method: 'PUT',
    url: "/api/students/" + studentId + "/cards",
    data: {
      cards: performance
    }
  });
};
Student.decks = function(studentId){
  return m.request({
    method: 'GET',
    url: "/api/students/" + studentId + "/decks"
  });
};
Student.toggleDeck = function(studentId, deckId){
  return m.request({
    method: 'PUT',
    url: "/api/students/" + studentId + "/decks",
    data: {
      deckId: deckId
    }
  });
};
module.exports = Student;