// Generated by LiveScript 1.2.0
var m, Student;
m = require('mithril');
Student = {};
Student.cards = function(studentId){
  return m.request({
    method: 'GET',
    url: "/api/students/" + studentId + "/cards"
  });
};
Student.sendStudentResult = function(performance){
  var studentId;
  studentId = m.route.param('id');
  return m.request({
    method: 'PUT',
    url: "/api/students/" + studentId + "/cards",
    data: {
      cards: performance
    }
  });
};
module.exports = Student;