// Generated by LiveScript 1.2.0
var m, User;
m = require('mithril');
User = {};
User.students = function(){
  return m.request({
    method: 'GET',
    url: '/api/students'
  });
};
User.changeStudentName = function(studentId, newName){
  return m.request({
    method: 'PUT',
    url: "/api/students/" + studentId,
    data: {
      studentName: newName
    }
  });
};
User.deleteStudent = function(studentId){
  return m.request({
    method: 'DELETE',
    url: "/api/students/" + studentId
  });
};
module.exports = User;