// Generated by LiveScript 1.2.0
var m, User;
m = require('mithril');
User = {};
User.students = function(){
  return m.request({
    method: 'GET',
    url: '/api/students'
  });
};
module.exports = User;