// Generated by LiveScript 1.2.0
var m, User;
m = require('mithril');
User = {
  students: function(){
    return m.request({
      method: 'GET',
      url: '/api/students'
    });
  },
  changeStudentName: function(studentId, newName){
    return m.request({
      method: 'PUT',
      url: "/api/students/" + studentId,
      data: {
        studentName: newName
      }
    });
  },
  deleteStudent: function(studentId){
    return m.request({
      method: 'DELETE',
      url: "/api/students/" + studentId
    });
  },
  createStudent: function(studentName){
    return m.request({
      method: 'POST',
      url: '/api/students',
      data: {
        studentName: studentName
      }
    });
  },
  decks: function(){
    return m.request({
      method: 'GET',
      url: '/api/decks'
    });
  },
  changeDeckName: function(deckId, newName){
    return m.request({
      method: 'PUT',
      url: "/api/decks/" + deckId,
      data: {
        deckName: newName
      }
    });
  },
  deleteDeck: function(deckId){
    return m.request({
      method: 'DELETE',
      url: "/api/decks/" + deckId
    });
  },
  createDeck: function(deckName){
    return m.request({
      method: 'POST',
      url: '/api/decks',
      data: {
        deckName: deckName
      }
    });
  }
};
module.exports = User;